In [1]:
print('Hello World')

Hello World


In [3]:
# importing numpy

import numpy as np 
print(f'Numpy version is {np.version.full_version}')

Numpy version is 1.14.3


## Numpy array

In [4]:
a = np.array([3,2,5,6,8,10])
print(f'Shape = {a.shape}')     # dont'know 
print(f'Dimension = {a.ndim}')  # dimension of array
print(f'A = {a}')
print(f'a[0] = {a[3]}')

Shape = (6,)
Dimension = 1
A = [ 3  2  5  6  8 10]
a[0] = 6


## Reshaping the arrray

In [5]:
# during reshape an array rwo value must be full filled
b = a.reshape(3,2)              # maikng this 'a' array into 3 dimensional arrayb`
print(f'Shape = {b.shape}')     # dont'know 
print(f'Dimension = {b.ndim}')  # dimension of array
print(f'A = {b}')
print(f'b[0][2] is {b[0][1]}')  # printing specific element of the array

Shape = (3, 2)
Dimension = 2
A = [[ 3  2]
 [ 5  6]
 [ 8 10]]
b[0][2] is 2


In [6]:
#printing type of the array
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [7]:
array1 = np.ones(4)  # creating an array with four 1
print(array1)

array2 = np.zeros(4) # creating an array with four 0
print(array2)

array2 = np.eye(4)   # creating 4 by 4 identity matrix 
print(array2)



[1. 1. 1. 1.]
[0. 0. 0. 0.]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
array3 = np.ones((4,4))  # creating an 4 by 4 array of 1
print('array 1 is = ')
print(array1)

array4 = np.zeros((4,4)) # creating an 4 by 4 array of 0
print('array 2 is = ')
print(f'array2 is {array2}')


array 1 is = 
[1. 1. 1. 1.]
array 2 is = 
array2 is [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
array5 = np.full((4,4),6)   # creating n by n dimensional array with custom data, here custom data is 6
print(array5)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [10]:
# adding two numpy array
mat1 = np.array([3,5,5,9,5,6,6,5,6])
mat1Reshape = mat1.reshape(3,3)
mat2 = np.array([3,5,5,9,5,6,6,5,9])
mat2Reshape = mat2.reshape(3,3)
mat3 = mat1Reshape+mat2Reshape
print(mat3)

[[ 6 10 10]
 [18 10 12]
 [12 10 15]]


In [11]:
# random array
r_array = np.random.random((4,4))
print(r_array)

[[0.19932876 0.2871861  0.04078841 0.84915917]
 [0.80619598 0.91073296 0.97142025 0.971979  ]
 [0.54539676 0.0282116  0.00280314 0.19458009]
 [0.70973298 0.9085028  0.05119748 0.07471873]]


In [12]:
# custom array of mix data
t1 = np.array([[0,5,0],[5,5,5.],(1+1j,3.,2.)])
print(t1)

[[0.+0.j 5.+0.j 0.+0.j]
 [5.+0.j 5.+0.j 5.+0.j]
 [1.+1.j 3.+0.j 2.+0.j]]


In [16]:
# making an array from range and give its data type
i = np.arange(1,15,dtype = np.int)
print(i)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [56]:
# exmaple addding two array
a = np.full((3,3),4)
b = np.full((3,3),3)
print('a = ')
print(a)
print('b = ')
print(b)
print('a+b = ')
print(a+b)

a = 
[[4 4 4]
 [4 4 4]
 [4 4 4]]
b = 
[[3 3 3]
 [3 3 3]
 [3 3 3]]
a+b = 
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [28]:
# making an array of specifying range by given amount of element
# this array maintains equal difference between consecutive two element
a =  np.linspace(1,9,5)
print(a)

[1. 3. 5. 7. 9.]


In [62]:
a = np.array([2,3])
b= np.array([2.,3.])
c= np.array([4,5],dtype = np.int64)
print(a.dtype,b.dtype,c.dtype)

int32 float64 int64
