In [3]:
# importing numpy
import numpy as np

In [8]:
# checking numpy version
print (f'numpy version is {np.version.full_version}')

numpy version is 1.14.3


In [61]:
#numpy arrray declaration
nparray = np.array([1,2,3,4,5,6])

# shape the numpy array
print (f'shape of the numpy array is = {nparray.shape}')

# dimension of the numpy array
print (f'dimesion of the numpy array is = {nparray.ndim}')

#printing the whole numpy array
print(f'nparray is = {nparray}')

#print element in an specific index of the numpy array
a = 4
print(f'element of the index {a} is = {nparray[a]}')

shape of the numpy array is = (6,)
dimesion of the numpy array is = 1
nparray is = [1 2 3 4 5 6]
element of the index 4 is = 5


In [62]:
# reshaping a numpy array
# during reshaping an onde dimensional array it is important to remember that
# every row the given new dimensional array must fullfilled
# for example if we reshape the above array as 3 by 2 array
# it will throw an error, because it is not possible making nparray
# as a 3 row and 2 column
reshapedarray = nparray.reshape(3,2) 
print (f'reshaped array is = \n {reshapedarray}')


reshaped array is = 
 [[1 2]
 [3 4]
 [5 6]]


In [63]:
# dimension of the reshapedarray
print(f'dimension of the reshaped array is = {reshapedarray.ndim}')


dimension of the reshaped array is = 2


In [64]:
# printing element of an specific index of the reshapedarray
# numpy array index always starts from 0
row = 2
col = 1 

print(f'element of the row {row} and column {col} is {reshapedarray[row][col]}')

element of the row 2 and column 1 is 6


In [65]:
# printing the type of the numpy array
print(f'type of the nparray is {type(nparray)}')
print(f'type of the nparray is {type(reshapedarray)}')

#both are numpy array

type of the nparray is <class 'numpy.ndarray'>
type of the nparray is <class 'numpy.ndarray'>


 ## numpy methods for quick array creation

In [78]:
# creating an one dimensional numpy array of value 1
# argument takes how many 1 we want
a = np.ones(5)  
print(a)

[1. 1. 1. 1. 1.]


In [83]:
# creating an one dimensional numpy array of value 0
# argument takes how many 0 we want
b = np.zeros(5)  
print(b)

[0. 0. 0. 0. 0.]


In [84]:
# creating n by n dimensional idenity matrix with numpy
# argument takes how many rows and column we want
c = np.eye(5)  
print(c)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [99]:
# creating an m by n dimensional matrix of the value 1
m = 4
n = 3
a1 = np.ones((m,n))
print(a1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [100]:
# creating an m by n dimensional matrix of the value 0
m = 4
n = 3
a2 = np.zeros((m,n))
print(a2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [109]:
# creating an m by n matrix by giving an specific element or custom element
m = 4
n = 3
elem = 12
a3 = np.full((m,n),elem)
print(a3)

[[12 12 12]
 [12 12 12]
 [12 12 12]
 [12 12 12]]


In [125]:
# addition of the two matrix using numpy

mat1 = np.full((4,2),3)
print(f'mat1 is \n {mat1}')
mat2 = np.full((4,1),4)
print(f'mat2 is \n {mat2}')
print(f'summation of mat1 and mat2 is \n{mat1+mat2}')


mat1 is 
 [[3 3]
 [3 3]
 [3 3]
 [3 3]]
mat2 is 
 [[4]
 [4]
 [4]
 [4]]
summation of mat1 and mat2 is 
[[7 7]
 [7 7]
 [7 7]
 [7 7]]


In [131]:
# maikng a random value matrix using numpy
rnarray = np.random.random((4,2))
print(rnarray)


[[0.7993592  0.93172772]
 [0.8460252  0.61834614]
 [0.57444658 0.60010492]
 [0.48105284 0.68939794]]


In [137]:
# making an custom np array with custom data

cstmnparray = np.array([[4,5,3],[1+0j,4,5],('shafi','rafi',5)])
print(cstmnparray)

[['4' '5' '3']
 ['(1+0j)' '4' '5']
 ['shafi' 'rafi' '5']]


In [141]:
# making an one d array by specifiying distance between consecutive elements and how many elements we want
anew = np.linspace(1,9,9)
print(anew)


[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [147]:
# printing and changing data type of the numpy array
a10 = np.array([5,6,8,9,10,11,12])
a11 = np.array([5,6,8,9,10,11,12])
a12 = np.array([5,6,8,9,10,11,12],dtype= np.int64)
print(a10.dtype,a11.dtype,a12.dtype)

int32 int32 int64
